version: '2'
services:
    proxy:
      build: .
      image: qiaodapei/shadowsocks-client:latest 
      container_name: ss_proxy
      environment:
        - SERVER=<your-server>
        - SERVER_PORT=<port>
        - PASSWORD=<your-password>
        - LOCAL_PORT=1080
        - TIMEOUT=60
        - METHOD=aes-256-cfb
      expose:
        - "1080"
      ports:
        - "1080:1080"
